// <auto-generated />
using System;
using ClaimRequest.DAL.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClaimRequest.DAL.Migrations
{
    [DbContext(typeof(ClaimRequestDbContext))]
    [Migration("20250213154901_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClaimRequest.DAL.Data.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<Guid>("ClaimerId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimer_id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("FinanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("remark");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalWorkingHours")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_working_hours");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id");

                    b.HasIndex("ClaimerId");

                    b.HasIndex("FinanceId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("ClaimRequest.DAL.Data.Entities.ClaimApprover", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_id");

                    b.HasKey("ClaimId", "ApproverId");

                    b.HasIndex("ApproverId");

                    b.ToTable("ClaimApprovers");
                });

            modelBuilder.Entity("ClaimRequest.DAL.Data.Entities.ClaimChangeLog", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("FieldChanged")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_changed");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.HasKey("HistoryId");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimChangeLogs");
                });

            modelBuilder.Entity("ClaimRequest.DAL.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("budget");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_manager_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProjectManagerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ClaimRequest.DAL.Data.Entities.ProjectStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ProjectRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StaffId");

                    b.ToTable("ProjectStaffs");
                });

            modelBuilder.Entity("ClaimRequest.DAL.Data.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("ClaimRequest.DAL.Data.Entities.Claim", b =>
                {
                    b.HasOne("ClaimRequest.DAL.Data.Entities.Staff", "Claimer")
                        .WithMany()
                        .HasForeignKey("ClaimerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaimRequest.DAL.Data.Entities.Staff", "Finance")
                        .WithMany()
                        .HasForeignKey("FinanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimRequest.DAL.Data.Entities.Project", "Project")
                        .WithMany("Claims")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claimer");

                    b.Navigation("Finance");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ClaimRequest.DAL.Data.Entities.ClaimApprover", b =>
                {
                    b.HasOne("ClaimRequest.DAL.Data.Entities.Staff", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimRequest.DAL.Data.Entities.Claim", "Claim")
                        .WithMany("ClaimApprovers")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimRequest.DAL.Data.Entities.ClaimChangeLog", b =>
                {
                    b.HasOne("ClaimRequest.DAL.Data.Entities.Claim", "Claim")
                        .WithMany("ChangeHistory")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimRequest.DAL.Data.Entities.Project", b =>
                {
                    b.HasOne("ClaimRequest.DAL.Data.Entities.Staff", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("ClaimRequest.DAL.Data.Entities.ProjectStaff", b =>
                {
                    b.HasOne("ClaimRequest.DAL.Data.Entities.Project", "Project")
                        .WithMany("ProjectStaffs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimRequest.DAL.Data.Entities.Staff", "Staff")
                        .WithMany("ProjectStaffs")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ClaimRequest.DAL.Data.Entities.Claim", b =>
                {
                    b.Navigation("ChangeHistory");

                    b.Navigation("ClaimApprovers");
                });

            modelBuilder.Entity("ClaimRequest.DAL.Data.Entities.Project", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("ProjectStaffs");
                });

            modelBuilder.Entity("ClaimRequest.DAL.Data.Entities.Staff", b =>
                {
                    b.Navigation("ProjectStaffs");
                });
#pragma warning restore 612, 618
        }
    }
}
